---
repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev:  v0.0.9
    hooks:
      - id: terraform-fmt
      - id: shellcheck

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.0
    hooks:
      - id: git-dirty

  # - repo: git://github.com/antonbabenko/pre-commit-terraform
  #   rev: v1.45.0 
  #   hooks:
  #     - id: terraform_docs
