plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- - "@semantic-release/exec"
  - verifyReleaseCmd: "echo ${nextRelease.version} > VERSION.txt"
- "@semantic-release/gitlab"
branches:
- "master"
